package group4.project.travelgoda.service;

import group4.project.travelgoda.dto.request.GenerateReportRequest;
import group4.project.travelgoda.dto.response.ReportResponse;

import java.util.List;

public interface ReportService {
    
    /**
     * Generate a financial report based on the given parameters
     * @param request Report generation request
     * @param userId User who is generating the report
     * @return Generated report data
     */
    ReportResponse generateReport(GenerateReportRequest request, Long userId);
    
    /**
     * Get all reports generated by a specific user
     * @param userId User ID
     * @return List of reports
     */
    List<ReportResponse> getReportsByUser(Long userId);
    
    /**
     * Get a specific report by ID
     * @param reportId Report ID
     * @return Report data
     */
    ReportResponse getReportById(Long reportId);
}
